### PR TITLE
Ryan10132/add api enhancements

### PR DESCRIPTION
**Pull request by ryan10132**
Adds optional ts types
Adds custom ts type parsing
Adds output stream support for output

### CODE REVIEW

**Comment by ryan10132** [comment]
Hi, I'm not sure why this is failing

**Comment by vojtechhabarta** [comment]
@ryan10132 part of the build are "upload maven site" and "tag build" steps. These steps do not work for PR builds. I'm trying to improve the build. Your code is compilable see line [2042](https://ci.appveyor.com/project/vojtechhabarta/typescript-generator/build/1.2.114-xub0vm6i#L2042) in build log.

Thanks for splitting the PR. Could you please just remove unnecessary changes in import statements? For example `GenerateTask.java` contains no real change and there are 20 lines changed. This is most obvious case but these extra changes are in many java files. In this project import statements are sorted alphabetically and wildcard imports can be used.

**Comment by ryan10132** [comment]
Alright, got it. I removed the unnecessary import changes. 

I'll run mvn test locally and decide if things are passing based on that in the future, thanks!

**Comment by vojtechhabarta** [comment]
Thanks for removing diffs in imports.
Meanwhile I improved build so it should work for PRs.

In current codebase it's not easy to implement and test custom Java to TypeScript type mapping. I think root cause is `ModelCompiler.typeFromJava()` method which is hard to reuse and its contract is confusing. It serves two purposes: 1. maps Java type to TypeScript type and 2. discovers classes used in Java type which should be also processed. This is not obvious from method signature which uses _output_ parametr.

So I will merge your PR and then try to refactor this method together with your changes into more flexible and clean code.

**Comment by ryan10132** [comment]
Cool, thanks, let me know what you come up with. I'll have another PR within a few hours for my next feature.

**Pull request merged**
