### PR TITLE
add Settings.customTypeNamingFunctionImpl

### PR DESCRIPTION
**Pull request by ruediste**
See #359

### CODE REVIEW

**Comment by vojtechhabarta** [comment]
I was thinking about adding something like this
``` java
public SymbolTable.CustomTypeNamingFunction customTypeNamingJavaFunction = null;
```
to `Settings` class so it is as close as possible to `customTypeNamingFunction` parameter.
What do you think?

**Comment by ruediste** [comment]
That was also my first shot. But I have seen the invocation `function.getName(cls.getName(), cls.getSimpleName())`, so I thought it might be better to just send the whole class to the function. Both are fine with me, your call.

**Comment by vojtechhabarta** [comment]
I think using `SymbolTable.CustomTypeNamingFunction` guaranties that this feature stays the same in JavaScript and Java in the future.

**Comment by ruediste** [comment]
Great. Adjusted.

**Comment by vojtechhabarta** [comment]
Merged, thanks.

**Comment by vojtechhabarta** [comment]
Released in [2.15](https://github.com/vojtechhabarta/typescript-generator/releases).

**Pull request merged**
