### PR TITLE
fix for generic types and Pageable

### PR DESCRIPTION
**Pull request by svpace**

### CODE REVIEW

**Comment by vojtechhabarta** [comment]
Thanks for this valuable PR.

May I just ask you to not make changes which are not necessary? I mean mainly changes in pom.xml file. I think you just need to add
``` xml
    <dependencyManagement>
        <dependencies>
            <dependency>
                <!-- Import dependency management from Spring Boot -->
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>2.1.2.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
```
and then
``` xml
        <dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-commons</artifactId>
        </dependency>
```
(and remove `<version>` element of `spring-boot-starter-web` dependency)

And that's it. Everything else can stay as it is now.

Also some changes in Java imports are not necessary but that's ok.

**Comment by svpace** [comment]
Sorry about that, I was trying to reduce the "dependency footprint". But I agree with you, this probably belongs in it's own PR. Fixed it.

**Comment by vojtechhabarta** [comment]
Merged.

I just changed `typescript-generator-core` dependencies to use values directly to be consistent with other pom.xml files, maybe in the future we can change whole project to use `${project.groupId}` and `${project.version}` variables.

Thank you very much.

**Comment by sergiopacezup** [comment]
Great! Thanks for the adjustments.
If you would like to change all the poms to use variables just let me know and I will prepare a PR.

**Comment by svpace** [comment]
Great! Thanks for the adjustments. If you would like to change all the poms to use variables just let me know and I will prepare a PR.

**Comment by pumpkinlink** [comment]
@svpace  I'm sorry but what exactly does this fix on generic types? All my `List<SpecificClass>` controllers are now being converted to `any[]`  instead of `SpecificClass[]`, is this expected behavior?

image

**Comment by svpace** [comment]
No, this is not expected. The fix was supposed to handle pure type
variables. Can you send me a java sample so I can track this down?

**Comment by pumpkinlink** [comment]
@svpace     

I was able to reproduce it with this sample controller
``` java
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.RequestMapping;
import java.util.Arrays;
import java.util.List;
import org.springframework.web.bind.annotation.PathVariable;

/**
 * REST controller for managing UserAccount.
 */
@RestController
@RequestMapping("/api")
public class UserAccountResource  {
    @GetMapping ( "/users/{id}/contacts" )
    public ResponseEntity< List<String> > getContacts ( @PathVariable Long id ) {
        List<String> contacts = Arrays.asList( "a" , "b" , "c" );
        return ResponseEntity.ok( contacts );
    }
}

```

**Comment by svpace** [comment]
@pumpkinlink thank you for the sample and sorry for the inconvenience. I've restored the previous handling of ResponseEntity. See #370. If you experience any other issues just let me know.

**Comment by vojtechhabarta** [comment]
Thanks @pumpkinlink for reporting the issue and @svpace for very quick fix.

This PR is released in [v2.15.526](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.15.526), fix in [v2.15.527](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.15.527).

**Comment by pumpkinlink** [comment]
Thank you guys for the quick fix/review/release.

This project is evolving very fast! I was able to remove hundreds of lines of code from both backend and frontend thanks to the support for Spring controllers and the Pageable object.

**Pull request merged**
