### PR TITLE
enable to configure maven scanning to avoid to scan the whole classpath

### PR DESCRIPTION
**Pull request by rmannibucau**

### CODE REVIEW

**Comment by vojtechhabarta** [comment]
I think it is not a good idea to allow excluding some artifacts from class path. This could lead to some errors due to inconsistent dependencies.

I would like to know what's the reason behind this feature, maybe it could be solved differently.

BTW typescript-generator-maven-plugin and typescript-generator-gradle-plugin should offer the same features.

**Comment by rmannibucau** [comment]
Idea is tobe able to exclude scanning of not needed dependencies, in my case 60 jars for 2 needed. It speeds up generation and will enable to reduce io/cpu usage which is way too high for what is generated on big projects.

**Comment by vojtechhabarta** [comment]
I thing instead of excluding artifacts from class path it would be safer to just limit which packages are scanned. ClassGraph library (which is used for class path scanning) has `whitelistPackages` method which allows to specify this. This feature was discussed in #330.

BTW what are your times without any optimisation?

**Comment by rmannibucau** [comment]
@vojtechhabarta between 4s (100% cpu) to 15 depending im on a ssd or plain old drive. Some deps are hugggeeee jars.
Package whitelisting will be slower cause you will go through the classloader.getResources if you optimize it and then it back this o(n) issue whereas this jar filtering makes it minimal. Also it will potentially miss zip index and if it is a big jar it will hurt.
In terms of safety i think it is very rare it is unsafe and the plugin could, worse case, fail in those case saying it misses a dep.

**Comment by vojtechhabarta** [comment]
I don't plan to add possibility to alter classpath for speed up purposes because I consider it dangerous. Sometimes people have issues with wrong classpath and I don't want to make this even worse.

But in version [2.29.814](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.29.814) I added [scanningAcceptedPackages](https://www.habarta.cz/typescript-generator/maven/typescript-generator-maven-plugin/generate-mojo.html#scanningAcceptedPackages) parameter which allows to speed up the classpath scanning by specifying allowed packages.

**Pull request closed without merging**
