### PR TITLE
ISSUE-489: Do not create constructors for Typescript interfaces

### PR DESCRIPTION
**Pull request by manstis**
See https://github.com/vojtechhabarta/typescript-generator/issues/489

### CODE REVIEW

**Comment by manstis** [comment]
I've also added a commit that fixes `JsonDeserializationExtension` when the `generateConstructors` flag has been set to `true` (in which cases there is no zero-parameter constructor generated and we need to pass the `data` parameter). 

I had to expose `Settings` to `ModelTransformer` - that I thought reasonable - IDK how you'd want to tackle backwards compatibility? I could keep the original methods on `ModelTransformer`, mark as deprecated and add new ones with the `Settings` parameter. The deprecated methods would call the new ones passing `null` and I'd add a `null` check before trying to ascertain whether constructors had been generated...

All good stuff.. enjoying this plugin so far :-)

**Comment by vojtechhabarta** [comment]
First commit (fixing constructors in interfaces) is clear. I would merge it.

Incompatibility in second commit is problematic. In typescript-generator I don't consider Java compatibility as important as compatibility of Maven and Gradle plugins (because it has fewer users and Java compiler can help) but this part of Java API is explicitly meant for users.

However I think in this case it is not needed to pass `Settings` to `ModelTransformer` method. Solution could be to detect if there is explicit constructor using `bean.getConstructor() != null` check (instead of `settings.generateConstructors`).

**Comment by manstis** [comment]
Thank-you @vojtechhabarta 

I will revise the second commit following your proposal and let you know when complete.

**Comment by manstis** [comment]
Hi @vojtechhabarta I've updated the second commit. 

Please let me know if you would like further changes.

**Comment by vojtechhabarta** [comment]
Hi @manstis,
thank you for your changes. Merging...

**Comment by manstis** [comment]
Hi @vojtechhabarta thank-you kindly.

My $1M question is.... when are you planning your next release?

It may not surprise you that I encountered the issue whilst using your plugin for a work task...

I have no strict deadline but knowledge of when you next plan to release would be helpful.

Thank-you,

Mike

**Comment by vojtechhabarta** [comment]
Hi Mike,
I usually plan release once a month. So it should be soon but I don't want to promise any date.
Vojta

**Comment by manstis** [comment]
Hi @vojtechhabarta no problem. 

I have months of development work remaining so no hurry.

**Comment by vojtechhabarta** [comment]
Released in [2.24.612](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.24.612).

**Pull request merged**
