### PR TITLE
Support for sealed classes containing tagged unions

### PR DESCRIPTION
**Pull request by Nthalk**
This uses the proposal of https://github.com/FasterXML/jackson-module-kotlin/issues/239 and the general solution of https://github.com/FasterXML/jackson-module-kotlin/pull/240 to import subtypes of a sealed object or interface that are annotated with `@JsonTypeName` and assignable to the container class or interface to create a much less verbose method of generating tagged unions.

Sealed types are supported in kotlin 1.6+ and Java 17+, however, we don't really need the sealed functionality, as we are an offline, one-shot generator, this may work to generate the correct type mappings, but fail to parse on the runtime object mapper side unless the user is using the supported kotlin and java versions.

### CODE REVIEW

**Comment by vojtechhabarta** [comment]
Hello @Nthalk, I checked your PR and I like the idea of using sealed classes for tagged unions instead of `@JsonSubTypes`. However your implementation only works for classes declared inside tagged union root class while ObjectMapper could be able to handle subclasses declared anywhere. So in c716d4f32211b6459ca11ee6bde1f27f22171580 I implemented this feature by getting list of subclasses directly from Jackson which can be configured with appropriate module for handling sealed classes.

I understand your use case of one-shot generator but I see value in generating TypeScript code corresponding as much as possible to runtime behaviour of ObjectMapper (with added modules). For your use case you just need to add Jackson module handling sealed classes.

**Comment by vojtechhabarta** [comment]
Here is an example of tagged union defined using Kotlin sealed class:

``` kotlin
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "type")
// @JsonSubTypes(
//     JsonSubTypes.Type(Rectangle::class),
//     JsonSubTypes.Type(Circle::class),
// )
sealed class Shape {
}

@JsonTypeName("rectangle")
class Rectangle(val a: Int, val b: Int) : Shape() {
}

@JsonTypeName("circle")
class Circle(val radius: Int) : Shape() {
}
```

It is needed to add `com.fasterxml.jackson.module.kotlin.KotlinModule` to typescript-generator configuration parameter `jackson2Modules`.

In this case typescript-generator recognizes tagged union root class by `@JsonTypeInfo` annotation and there is no need for `@JsonSubTypes`.

For Java it is similar but currently there is no publicly available Jackson module for Java sealed classes. You can check example of such module in https://github.com/vojtechhabarta/typescript-generator/commit/c716d4f32211b6459ca11ee6bde1f27f22171580#diff-58156e5b6e0095f0b6f2173780b20ec0d7474cfca48257a44c68da1d75a0ef54, unfortunately it is commented out because typescript-generator build needs to run on Java 11.

**Comment by Nthalk** [comment]
Awesome, I'll close this PR out then. When can we expect the next release? =D

**Comment by vojtechhabarta** [comment]
Just released as part of [3.2.1263](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v3.2.1263).

**Pull request closed without merging**
