### PR TITLE
add PropertyPolymorphismExtension

### PR DESCRIPTION
**Pull request by ruediste**
This is a first implementation.  What do you think? See also #397

### CODE REVIEW

**Comment by vojtechhabarta** [comment]
So far it looks good.

Do you plan to make it usable from Maven and Gradle? We discussed using annotations so I think you can implement `isPolymorphicBase` and `getPropertyName` abstract methods and allow user to specify annotations used for polymorphism. You can override `setConfiguration` method to get those values from user. Then Maven and Gradle users can use `extensionsWithConfiguration` parameter to configure your extension.

BTW in 48b30bd76998c8e35f99a727801566b7fabe730d I added `NeedBraces` Checkstyle rule to keep codebase more consistent.

**Comment by ruediste** [comment]
No I added the `setConfiguration()` implementation and some javadocs.

**Comment by vojtechhabarta** [comment]
I just briefly checked it. Do you plan to add some changes or should I merge it? If it is usable for you I would merge it.

**Comment by ruediste** [comment]
No further changes planned, please merge. Thanks.

**Comment by vojtechhabarta** [comment]
Merged, thanks for this extension.

**Comment by vojtechhabarta** [comment]
Released in version [2.17.558](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.17.558).

**Pull request merged**
